---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-deployment
spec:
  selector:
    matchLabels:
      app: office
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: office
    spec:
      containers:
      - name: office
        image: saboora/office:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: office-service
  labels:
    app: office
spec:
  ports:
  - port: 80
    protocol: TCP

